export const THEME = {
  primary: '#163b0f',
  parchment: '#fbf6f1',
};

export const PROPERTIES = [
  {
    id: '1',
    title: 'The Penthouse Suite',
    price: '4.2M',
    sqm: '320',
    type: 'Sale',
    status: 'Available',
    location: 'Luxembourg City',
    bedrooms: 4,
    bathrooms: 3,
    image: 'https://images.unsplash.com/photo-1600607687940-4e7a6a353d39?auto=format&fit=crop&q=80&w=1200',
    amenities: ['Private Elevator', 'Roof Terrace', 'Wine Cellar'],
    description: 'A masterpiece of modern architecture offering horizon-deep views and expansive ceilings.',
  },
  {
    id: '2',
    title: 'Sky Loft Residence',
    price: '1.8M',
    sqm: '180',
    type: 'Sale',
    status: 'Available',
    location: 'Kirchberg',
    bedrooms: 2,
    bathrooms: 2,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0bb2a6c3e?auto=format&fit=crop&q=80&w=1200',
    amenities: ['Floor-to-ceiling Windows', 'Smart Home', 'Concierge'],
    description: 'Contemporary living at its finest, located in the heart of the financial district.',
  },
  {
    id: '3',
    title: 'Garden Duplex',
    price: '2.5M',
    sqm: '240',
    type: 'Rent',
    status: 'Available',
    location: 'Limpertsberg',
    bedrooms: 3,
    bathrooms: 2,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200',
    amenities: ['Private Garden', 'Double Garage', 'Fireplace'],
    description: 'A serene oasis combining historical charm with modern luxury.',
  },
  {
    id: '4',
    title: 'Forest Edge Villa',
    price: '5.5M',
    sqm: '450',
    type: 'Sale',
    status: 'Reserved',
    location: 'Senningerberg',
    bedrooms: 5,
    bathrooms: 4,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&q=80&w=1200',
    amenities: ['Infinity Pool', 'Home Cinema', 'Guest House'],
    description: 'Ultimate privacy meets sophisticated design in this forest-side retreat.',
  },
];

export const SERVICES = [
  {
    title: 'Real Estate Agency',
    description: 'A comprehensive, full-service approach to buying and selling premium properties across Luxembourg. Our agents combine deep local market knowledge with an international perspective to secure the finest outcomes for our clients.',
    details: 'From initial consultation to the final signing, we manage every detail of your transaction with the precision and discretion that distinguished clientele deserves.',
    features: [
      'Exclusive Off-Market & Private Listings',
      'In-depth Property Valuation & Market Analysis',
      'Negotiation Strategy & Offer Management',
      'Full Transaction Coordination & Oversight',
      'Post-Sale Support, Aftercare & Relocation Assistance',
    ],
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&q=80&w=1200',
  },
  {
    title: 'Real Estate Legal Advice',
    description: 'Rigorous legal expertise applied at every stage of your real estate journey. Our in-house legal team ensures every contract, clause, and compliance obligation is reviewed with absolute precision to protect your interests.',
    details: 'We navigate Luxembourgish property law, cross-border regulations, and thorough due diligence with meticulous attention to detail and unwavering authority.',
    features: [
      'Contract Drafting, Review & Amendment',
      'Full Due Diligence & Title Verification',
      'Cross-Border & EU Regulation Compliance',
      'Notarial Act Preparation & Coordination',
      'Dispute Resolution, Mediation & Litigation Support',
    ],
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=1200',
  },
];
